var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/signup/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_upko4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ul73e7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_05balh5.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ioo8cy._.js")
R.c("server/chunks/ssr/node_modules_next_dist_03nkrli._.js")
R.c("server/chunks/ssr/src_app_layout_tsx_0fhx__n._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_signup_page_actions_01t.ngc.js")
R.m(68893)
module.exports=R.m(68893).exports
